### ISSUE TITLE
When this happens, the cursor size becomes larger. Killing the terminal and opening a new one fixes the problem. Resizing vscode also helps to fix the issue.

### ISSUE THREAD

**Issue by Ericsandanu** [microsoft/DeepSpeed#4465]
[adcookies.xlsx](https://github.com/microsoft/DeepSpeed/files/12832938/adcookies.xlsx)
[Anda memiliki akses - Microsoft Azure.docx](https://github.com/microsoft/DeepSpeed/files/12832939/Anda.memiliki.akses.-.Microsoft.Azure.docx)
[Buku.xlsx](https://github.com/microsoft/DeepSpeed/files/12832941/Buku.xlsx)
[BingAnswers-20230804-044607.xlsx](https://github.com/microsoft/DeepSpeed/files/12832942/BingAnswers-20230804-044607.xlsx)
[BulkActions.docx](https://github.com/microsoft/DeepSpeed/files/12832943/BulkActions.docx)
[BulkActions.txt](https://github.com/microsoft/DeepSpeed/files/12832944/BulkActions.txt)
[DefaultViewIndexerLog.txt](https://github.com/microsoft/DeepSpeed/files/12832946/DefaultViewIndexerLog.txt)
[Dokumen.docx](https://github.com/microsoft/DeepSpeed/files/12832947/Dokumen.docx)
[FilterFolders.txt](https://github.com/microsoft/DeepSpeed/files/12832949/FilterFolders.txt)
[Google Passwords.xlsx](https://github.com/microsoft/DeepSpeed/files/12832950/Google.Passwords.xlsx)
[hCAPTCHA Demo (1).txt](https://github.com/microsoft/DeepSpeed/files/12832951/hCAPTCHA.Demo.1.txt)
[hCAPTCHA Demo.txt](https://github.com/microsoft/DeepSpeed/files/12832952/hCAPTCHA.Demo.txt)
[InboxRules.txt](https://github.com/microsoft/DeepSpeed/files/12832954/InboxRules.txt)
[Instructors can prepare for their virtual learning environment by implementing specific strategies for each element of hybrid learning.docx](https://github.com/microsoft/DeepSpeed/files/12832955/Instructors.can.prepare.for.their.virtual.learning.environment.by.implementing.specific.strategies.for.each.element.of.hybrid.learning.docx)
[LegacySettings.txt](https://github.com/microsoft/DeepSpeed/files/12832956/LegacySettings.txt)

[IMG20230831101130](https://github.com/microsoft/DeepSpeed/assets/100530119/e1e06363-193d-4e31-bb70-c84807fe9c11)
[IMG20230831101344](https://github.com/microsoft/DeepSpeed/assets/100530119/26da8fa8-e6b8-4f71-a399-57c8bad7ffe3)
 
 When this happens, the cursor size becomes larger. Killing the terminal and opening a new one fixes the problem. Resizing vscode also helps to fix the issue.

https://github.com/microsoft/vscode/assets/16353531/62d61227-dab2-441c-918e-6d5c08228ee8

_Originally posted by @EricsandanuMnsn in https://github.com/microsoft/vscode/issues/194156#issuecomment-1742046845_
            
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/DeepSpeed/pull/4312
- [ ] https://github.com/microsoft/DeepSpeed/issues/4443
- [ ] https://github.com/microsoft/DeepSpeed/pull/4434
- [ ] https://github.com/microsoft/DeepSpeed/pull/4325
- [ ] https://github.com/microsoft/DeepSpeed/pull/4326
- [ ] https://github.com/microsoft/DeepSpeed/issues/4464
- [ ] https://github.com/microsoft/DeepSpeed/pull/4451
- [ ] https://github.com/microsoft/DeepSpeed/pull/4327
- [ ] https://github.com/microsoft/DeepSpeed/pull/3727
- [ ] https://github.com/microsoft/DeepSpeed/pull/4318
- [ ] https://github.com/microsoft/DeepSpeed/pull/4343
- [ ] https://github.com/microsoft/DeepSpeed/pull/4461
- [ ] https://github.com/microsoft/DeepSpeed/issues/2684
- [ ] https://github.com/microsoft/DeepSpeed/issues/3857
- [ ] https://github.com/microsoft/DeepSpeed/issues/3779
- [ ] https://github.com/microsoft/DeepSpeed/issues/4463
- [ ] https://github.com/microsoft/DeepSpeed/issues/4455
- [ ] https://github.com/microsoft/DeepSpeed/issues/4125
- [ ] https://github.com/microsoft/DeepSpeed/pull/4331
- [ ] https://github.com/microsoft/DeepSpeed/pull/4206
- [ ] https://github.com/microsoft/DeepSpeed/issues/4462
- [ ] https://github.com/microsoft/DeepSpeed/pull/4452
- [ ] https://github.com/microsoft/DeepSpeed/issues/4447
- [ ] https://github.com/microsoft/DeepSpeed/issues/4380
- [ ] https://github.com/microsoft/DeepSpeed/pull/4450
- [ ] https://github.com/microsoft/DeepSpeed/issues/3992
- [ ] https://github.com/microsoft/DeepSpeed/issues/2928
- [ ] https://github.com/microsoft/DeepSpeed/issues/2921
- [ ] https://github.com/microsoft/DeepSpeed/issues/3811
- [ ] https://github.com/microsoft/DeepSpeed/issues/4272
- [ ] https://github.com/microsoft/DeepSpeed/issues/4460
- [ ] https://github.com/microsoft/DeepSpeed/issues/4459
- [ ] https://github.com/microsoft/DeepSpeed/issues/2099
- [ ] https://github.com/microsoft/DeepSpeed/pull/4458
- [ ] https://github.com/microsoft/DeepSpeed/pull/4457
- [ ] https://github.com/microsoft/DeepSpeed/pull/4456
- [ ] https://github.com/microsoft/DeepSpeed/pull/4454
- [ ] https://github.com/microsoft/DeepSpeed/pull/4388
- [ ] https://github.com/microsoft/DeepSpeed/issues/4417
- [ ] https://github.com/microsoft/DeepSpeed/pull/4282
- [ ] https://github.com/microsoft/DeepSpeed/pull/4230
- [ ] https://github.com/microsoft/DeepSpeed/issues/4080
- [ ] https://github.com/microsoft/DeepSpeed/issues/4060
- [ ] https://github.com/microsoft/DeepSpeed/pull/4322
- [ ] https://github.com/microsoft/DeepSpeed/pull/4449
- [ ] https://github.com/microsoft/DeepSpeed/pull/3962
- [ ] https://github.com/microsoft/DeepSpeed/issues/4448
- [ ] https://github.com/microsoft/DeepSpeed/pull/4389
- [ ] https://github.com/microsoft/DeepSpeed/issues/4442
- [ ] https://github.com/microsoft/DeepSpeed/issues/4428
- [ ] https://github.com/microsoft/DeepSpeed/pull/4446
- [ ] https://github.com/microsoft/DeepSpeed/issues/4315
- [ ] https://github.com/microsoft/DeepSpeed/pull/4378
- [ ] https://github.com/microsoft/DeepSpeed/pull/4438
- [ ] https://github.com/microsoft/DeepSpeed/pull/4439
- [ ] https://github.com/microsoft/DeepSpeed/pull/4432
```

```[tasklist]
### Tasks
```

**Comment by tjruwase** [comment]
Not a deepspeed issue.
